# Generated by Django 3.2.9 on 2022-03-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transcribe_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcribe',
            old_name='owner',
            new_name='file',
        ),
    ]
