# Generated by Django 3.2.9 on 2022-03-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_owner_transcribe_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribe',
            name='file',
        ),
    ]
