# Generated by Django 3.2.9 on 2022-03-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_transcribe_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribe',
            name='file',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, to='core.file'),
            preserve_default=False,
        ),
    ]
