# Generated by Django 3.2.9 on 2022-03-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transcribe_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcribe',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
    ]
